name: Nick Platt
description: Notes from a systems software engineer
meta_description: Notes from a systems software engineer

url: 'https://nick-platt.com'

sass:
  style: compressed

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
