name: Nick Platt
description: Notes from a systems software engineer
meta_description: Notes from a systems software engineer

baseurl: /

sass:
  style: compressed

gems:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
