title: Nick Platt
url: https://nickp.co
email: platt.nicholas@gmail.com
github_username: caipre
description: >-
  Personal site for Nick Platt

permalink: /:year/:month/:title
include:
- _redirects

markdown: kramdown
sass:
  style: compressed
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-seo-tag
- jemoji


defaults:
- scope:
    path: .
    type: posts
  values:
    layout: post

gtag: 'UA-132738950-1'

