title: Nick Platt
url: https://nickp.co
email: platt.nicholas@gmail.com
github_username: caipre
description: >-
  Personal site for Nick Platt

sass:
  style: compressed

markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag

defaults:
- scope:
    path: .
    type: posts
  values:
    layout: post

gtag: 'UA-132738950-1'

