backend:
  name: github
  repo: caipre/caipre.github.io
  site_domain: loving-stonebraker-413f1e.netlify.com

publish_mode: editorial_workflow
media_folder: images/uploads

collections:
- name: blog
  label: Blog
  folder: _posts/
  create: true
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  fields:
  - label: Layout
    name: layout
    widget: hidden
    default: post
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: date
    widget: datetime
  - label: Tags
    name: tags
    widget: list
  - label: Body
    name: body
    widget: markdown
